### ISSUE TITLE
Webpack 5 compatibility

### ISSUE THREAD

**Issue by Jack-Works** [crimx/webpack-target-webextension#2]
This library depends on webpack/lib/FunctionModulePlugin but it is removed in Webpack 5

**Comment by crimx** [comment]
The code of the custom target is based on "web" target in Webpack 4 which is the Webpack version that Neutrinojs is depending.

**Comment by crimx** [comment]
Once Webpack 5 is mature enough and is adapted by Neutrinojs the code should change accordingly.

**Comment by Jack-Works** [comment]
hi, @crimx webpack 5 has released!

**Comment by crimx** [comment]
> hi, @crimx webpack 5 has released!

Good to know! Would you like to make a PR? Since my projects are based on Neutrino which [is still on 4](https://github.com/neutrinojs/webpack-chain/issues/266), I am not in a hurry to upgrade to Webpack 5 until my next new project.

**Comment by Jack-Works** [comment]
Ah I'm not familiar with webpack internal. Maybe I need to test if `writeToDisk` in webpack 5 still works

**Comment by A-gambit** [comment]
Hey @crimx. Do you have a plan to switch it to Webpack 5?

**Comment by crimx** [comment]
Not at the moment unfortunately. Still waiting for neutrinojs.

For browser extension development webpack 4 is more than enough though.

**Comment by A-gambit** [comment]
If we will think in the direction `technology X is more than enough for something` we will still use grunt to our codebase. Haha

**Comment by crimx** [comment]
> But if we will think in the direction technology X is more than enough for something we will still use grunt for our codebase.

If it works well I don't see anything wrong with using grunt which is still a powerful tool.

> Webpack 5 gives a lot of improvements in tree-shacking which can be helpful.

In browser extension bundle size has very little impact since they are loaded from the filesystem.

**Comment by Jack-Works** [comment]
I like new `new Worker("./x.js", import.meta.url)` and `new URL('./x.png', import.meta.url)` support in Webpack 5, hope I can use it so it would be nice to upgrade to 5
