### ISSUE TITLE
Does HMR works on this target?

### ISSUE THREAD

**Issue by Jack-Works** [crimx/webpack-target-webextension#3]
https://github.com/crimx/webpack-target-webextension/blob/master/lib/WebExtMainTemplatePlugin.js#L522

![](https://user-images.githubusercontent.com/5390719/94445261-d2bc0300-01d9-11eb-9f15-11162166bbb7.png)

I have debugged into the webpack and it seems like this library doesn't return a template that web extension can run on.

**Comment by crimx** [comment]
To enable HMR you have to run in fake env like what neutrino-webextension did. Real extension env does not support HMR.

**Comment by Jack-Works** [comment]
It does support. You just have to do some tweaks.

**Comment by Jack-Works** [comment]
I'd like to PR for HMR. Is that OK?

**Comment by crimx** [comment]
> I'd like to PR for HMR. Is that OK?

That would be great! PRs are welcomed.

**Comment by Jack-Works** [comment]
@crimx hi plz review and try it!

**Comment by crimx** [comment]
Great! I'll look into it as soon as possible.

**Comment by Jack-Works** [comment]
As you can see in the PR, I require some changes in the webpack config. Does that possible to auto-apply them in the plugin? @crimx
