### ISSUE TITLE
Rewrite HMR client?

### ISSUE THREAD

**Issue by Jack-Works** [crimx/webpack-target-webextension#5]
Hi, I'd like to know is it possible for a webpack plugin to re-write the HMR client?

When running HMR in the content script, for an unknown reason it will be blocked by CSP policy.

> Refused to connect to 'https://localhost:8080/sockjs-node/info?t=1603432704212' because it violates the following Content Security Policy directive: ......

If it is possible, I'd like to contribute an HMR client that works for the Web Extension.

**Comment by crimx** [comment]
> for an unknown reason it will be blocked by CSP policy.

This is because [content scripts follow the host page CSP policy](https://developer.chrome.com/extensions/contentSecurityPolicy#interactions). 

I think you'll have to leverage the background script to proxy the requests. 

> is it possible for a webpack plugin to re-write the HMR client?

I am not expert on this but judging by the fact that the HMR client is from webpack-dev-server I don't think it's possible.

**Comment by crimx** [comment]
How about disabling CSP like [this one](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en)?

**Comment by Jack-Works** [comment]
Yeah, I tried to find an extension to disable CSP but it work in a half-half chance

**Comment by Jack-Works** [comment]
I found a something interesting in webpack dev server config, I will try to investigate it later

**Comment by Jack-Works** [comment]
I found there is an option called [**`devServer.transportMode.client`**](https://webpack.js.org/configuration/dev-server/#devservertransportmodeclient). I don't know what it means clearly but it looks like a possible way to resolve.

And I found maybe I don't need one, maybe I just misconfigured my webpack config.

**Comment by crimx** [comment]
Cool. Looks like it's exactly what you want.

**Comment by Jack-Works** [comment]
hi, @crimx I found that I actually report a CSP error in a user script. In the content script, it won't be limited to connect to localhost.

**Comment by crimx** [comment]
What do you mean? So no change is required for this to work?

**Comment by Jack-Works** [comment]
The content script itself will not be affected by the host CSP policy. The script that content script appended to the document will so nothing is needed to change
